Repository INN/umbrella-citylimits, pull requests merged in 2019-10, with the labels that each got.

#60 Remove child-style.less, make grunt use style.less
  wp-content/themes/citylimits/Gruntfile.js
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/child-style.less
  wp-content/themes/citylimits/less/style.less
Labels: Estimate: <2

#75 Only show special projects in mobile nav if on homepage
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/homepages/assets/css/homepage.css
  wp-content/themes/citylimits/less/_navbar.less
  wp-content/themes/citylimits/partials/nav-sticky.php
Labels: Status: Review Needed

#66 Footer layout and styling
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/footer.php
  wp-content/themes/citylimits/img/facebook-hover.svg
  wp-content/themes/citylimits/img/facebook.svg
  wp-content/themes/citylimits/img/footer-skyline.png
  wp-content/themes/citylimits/img/instagram-hover.svg
  wp-content/themes/citylimits/img/instagram.svg
  wp-content/themes/citylimits/img/linkedin-hover.svg
  wp-content/themes/citylimits/img/linkedin.svg
  wp-content/themes/citylimits/img/list-arrow.png
  wp-content/themes/citylimits/img/twitter-hover.svg
  wp-content/themes/citylimits/img/twitter.svg
  wp-content/themes/citylimits/img/youtube-hover.svg
  wp-content/themes/citylimits/img/youtube.svg
  wp-content/themes/citylimits/less/footer.less
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/partials/footer-city-limits.php
Labels: Estimate: <4, Status: Review Needed

#79 SCAMP ad widget styles
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/_variables.less
  wp-content/themes/citylimits/less/ads.less
  wp-content/themes/citylimits/less/style.less
Labels: Estimate: <4, Status: Blocked, Status: Needs technical details

#78 Homepage special projects secondary nav
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/less/_navbar.less
  wp-content/themes/citylimits/partials/nav-main.php
Labels: Status: Review Needed

#80 Podcasting widget
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/inc/widgets/class-citylimits-podcast-widget.php
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/less/widget-citylimits-podcast.less
  wp-content/themes/citylimits/partials/widget-content.php
Labels: Estimate: <4

#81 Site header
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/header-rezone.php
  wp-content/themes/citylimits/header.php
  wp-content/themes/citylimits/js/navigation.js
  wp-content/themes/citylimits/less/_navbar.less
  wp-content/themes/citylimits/less/_variables.less
  wp-content/themes/citylimits/less/header.less
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/partials/nav-sticky.php
Labels: Status: Review Needed
