Repository INN/umbrella-citylimits, pull requests merged in 2019-11, with the labels that each got.

#86 Use `largo-modernizr` as dependency for `citylimits-navigation`
  wp-content/themes/citylimits/functions.php
Labels: Status: Review Needed

#88 Add a Special Projects template, and format its header
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/series-landing-special-projects.less
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/series-landing-special-projects.php
Labels: Priority: High, Status: Review Needed

#97 Special Projects Secondary Nav
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/js/navigation.js
  wp-content/themes/citylimits/less/series-landing-special-projects.less
  wp-content/themes/citylimits/package-lock.json
  wp-content/themes/citylimits/series-landing-special-projects.php
Labels: Status: Review Needed

#98 Special projects "Latest news" section: 7 posts from the series
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/homepages/assets/css/homepage.css
  wp-content/themes/citylimits/homepages/assets/less/homepage.less
  wp-content/themes/citylimits/inc/widgets/class-citylimits-series-posts-continued.php
  wp-content/themes/citylimits/inc/widgets/class-citylimits-series-seven-stories-widget.php
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/less/widget-citylimits-series-seven-stories.less
  wp-content/themes/citylimits/series-landing-special-projects.php
Labels: Status: Review Needed

#100 Special projects "featured content area" widget
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/inc/widgets/class-citylimits-special-projects-featured-content-widget.php
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/less/widget-citylimits-special-projects-featured-content.less
  wp-content/themes/citylimits/partials/content-series-featured-content-widget.php
Labels: Status: Review Needed

#101 Pullquote styling
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/inc/block-color-palette.php
  wp-content/themes/citylimits/less/typography.less
Labels: Status: Review Needed

#99 Create article template, style header
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/footer.less
  wp-content/themes/citylimits/less/single-two-column.less
  wp-content/themes/citylimits/less/social.less
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/single-two-column.php
Labels: Estimate: <2

#104 54 custom donation block
  wp-content/themes/citylimits/blocks/citylimits-custom-donate.php
  wp-content/themes/citylimits/blocks/citylimits-custom-donate/editor.css
  wp-content/themes/citylimits/blocks/citylimits-custom-donate/index.js
  wp-content/themes/citylimits/blocks/citylimits-custom-donate/style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/img/footer-skyline.png
Labels: Estimate: <4, Status: Review Needed

#109 #105 fonts, #108 homepage QA, #56 drop cap
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/css/job-board.css
  wp-content/themes/citylimits/homepages/assets/css/homepage.css
  wp-content/themes/citylimits/homepages/assets/less/homepage.less
  wp-content/themes/citylimits/inc/block-color-palette.php
  wp-content/themes/citylimits/inc/enqueue.php
  wp-content/themes/citylimits/less/_gallery.less
  wp-content/themes/citylimits/less/_navbar.less
  wp-content/themes/citylimits/less/_variables.less
  wp-content/themes/citylimits/less/ads.less
  wp-content/themes/citylimits/less/job-board.less
  wp-content/themes/citylimits/less/mixins.less
  wp-content/themes/citylimits/less/newsletters.less
  wp-content/themes/citylimits/less/series-landing-special-projects.less
  wp-content/themes/citylimits/less/single-two-column.less
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/less/top-tag.less
  wp-content/themes/citylimits/less/typography.less
  wp-content/themes/citylimits/less/widget-citylimits-series-seven-stories.less
  wp-content/themes/citylimits/less/widget-citylimits-special-projects-featured-content.less
  wp-content/themes/citylimits/less/widget-citylimits-special-projects.less
Labels: Priority: High

#106 Survey styling
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/less/widget-gravityforms-survey.less
Labels: Status: Review Needed

#113 QA meeting updates
  wp-content/themes/citylimits/blocks/citylimits-custom-donate/style.css
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/homepages/assets/css/homepage.css
  wp-content/themes/citylimits/homepages/assets/less/homepage.less
  wp-content/themes/citylimits/less/_navbar.less
  wp-content/themes/citylimits/less/ads.less
  wp-content/themes/citylimits/less/header.less
  wp-content/themes/citylimits/less/single-two-column.less
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/less/typography.less
  wp-content/themes/citylimits/less/widget-citylimits-podcast.less
  wp-content/themes/citylimits/less/widget-citylimits-special-projects.less
Labels: Status: Review Needed

#114 Bandaid fix for play icon appearing on special projects widget :(
  wp-content/themes/citylimits/inc/widgets/class-citylimits-series-seven-stories-widget.php
  wp-content/themes/citylimits/inc/widgets/class-citylimits-special-projects-featured-content-widget.php
  wp-content/themes/citylimits/inc/widgets/class-citylimits-special-projects-widget.php
Labels: Status: Review Needed

#118 Updates based on issues described in #115
  wp-content/themes/citylimits/less/series-landing-special-projects.less
Labels: Status: Review Needed

#112 49 newsletter changes
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/inc/enqueue.php
  wp-content/themes/citylimits/inc/widgets/cl-newsletter-header.php
  wp-content/themes/citylimits/inc/widgets/class-citylimits-special-projects-featured-content-widget.php
  wp-content/themes/citylimits/js/newsletter.js
  wp-content/themes/citylimits/less/_variables.less
  wp-content/themes/citylimits/less/footer.less
  wp-content/themes/citylimits/less/header.less
  wp-content/themes/citylimits/less/newsletters.less
  wp-content/themes/citylimits/less/page-newsletter-subscriptions.less
  wp-content/themes/citylimits/less/series-landing-special-projects.less
  wp-content/themes/citylimits/less/style.less
  wp-content/themes/citylimits/page-communitywire.php
  wp-content/themes/citylimits/partials/newsletter-signup-footer.php
  wp-content/themes/citylimits/partials/newsletter-signup-header.php
  wp-content/themes/citylimits/partials/newsletter-signup-maincolumn.php
  wp-content/themes/citylimits/partials/newsletter-signup-popover.php
Labels: Estimate: <8

#120 Special projects link list styles
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/series-landing-special-projects.less
Labels: Status: Review Needed

#122 Update homepage special project section mobile display
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/widget-citylimits-special-projects.less
Labels: Status: Review Needed

#123 Cachebust :allthethings:
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/inc/enqueue.php
  wp-content/themes/citylimits/inc/job-board.php
  wp-content/themes/citylimits/inc/metaboxes.php
Labels: Priority: High

#128 Remove trailing commas
  wp-content/themes/citylimits/inc/metaboxes.php
Labels: Status: Review Needed

#129 Styling for tan background link lists
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/less/series-landing-special-projects.less
Labels: Status: Review Needed

#130 Create widget based on The Neighborhoods map
  wp-content/themes/citylimits/css/child-style.css
  wp-content/themes/citylimits/functions.php
  wp-content/themes/citylimits/inc/widgets/class-citylimits-the-neighborhoods-map-widget.php
  wp-content/themes/citylimits/less/style.less
Labels: Status: Review Needed
